/* ==========================================================================
   Hélène of the West — experience catalogue
   Single source of truth for the Experiences grid, the detail template
   and the booking flow. When a real inventory API exists, replace this
   module with a fetch to that API — the shape below is the contract.
   ========================================================================== */

const CATEGORIES = {
  beaches: 'Beaches',
  rainforest: 'Rainforest & Hiking',
  pitons: 'Pitons & Sulphur Springs',
  culinary: 'Culinary & Rum',
  cultural: 'Cultural Tours',
  transfers: 'Private Transfers',
};

const EXPERIENCES = [
  {
    id: 'gros-piton-hike',
    title: 'Gros Piton Sunrise Hike',
    category: 'pitons',
    blurb: 'Summit Saint Lucia’s most famous peak with a certified local guide, before the heat of the day.',
    duration: '4–5 hours',
    group: 'Up to 8 guests',
    maxGuests: 8,
    price: 95,
    pricingUnit: 'person',
    img: 'assets/img/gros-piton-hike.svg',
    gallery: ['assets/img/gros-piton-hike.svg', 'assets/img/tet-paul.svg', 'assets/img/hero-pitons.svg'],
    times: ['4:30 AM', '5:00 AM', '5:30 AM'],
    meetingPoint: 'Fond Gens Libres Interpretive Centre, Soufrière — or hotel pickup on the west coast.',
    description: [
      'Gros Piton rises 798 metres straight out of the Caribbean Sea, and there is no better way to meet it than in the half-light before dawn. Your guide — born and raised in Fond Gens Libres, the village at the mountain’s foot — sets a steady, unhurried pace up the trail, pausing at the quarter and halfway lookouts as the sky turns from grey to gold.',
      'The summit opens onto a view that takes in Petit Piton, the Soufrière valley and, on a clear morning, Saint Vincent on the southern horizon. There is time at the top for photographs, fresh fruit and a proper rest before the descent.',
      'This is a genuine hike with steep sections, but no technical climbing. A reasonable level of fitness is all that is required, and our guides are experienced with first-time hikers.',
    ],
    included: ['Certified Piton guide', 'National trail fee', 'Bottled water and fresh fruit at the summit', 'Round-trip hotel transfer from Soufrière and the west coast'],
    bring: ['Sturdy closed shoes', 'Light rain layer', 'Sunscreen and a hat for the descent', 'A camera you don’t mind carrying'],
  },
  {
    id: 'sulphur-springs',
    title: 'Sulphur Springs & Toraille Waterfall',
    category: 'pitons',
    blurb: 'Drive into the world’s only drive-in volcano, soak in the mineral mud baths, then rinse off under a rainforest waterfall.',
    duration: '3 hours',
    group: 'Up to 10 guests',
    maxGuests: 10,
    price: 75,
    pricingUnit: 'person',
    img: 'assets/img/sulphur-springs.svg',
    gallery: ['assets/img/sulphur-springs.svg', 'assets/img/rainforest-waterfall.svg', 'assets/img/botanical-gardens.svg'],
    times: ['9:00 AM', '11:00 AM', '1:00 PM'],
    meetingPoint: 'Soufrière town square, or hotel pickup between Castries and Soufrière.',
    description: [
      'The Sulphur Springs at La Soufrière are the island’s geothermal heart — a caldera you can drive straight into, where steam vents and bubbling pools have drawn visitors since the eighteenth century. A park guide walks you through the science and the stories before you sink into the warm, mineral-rich mud baths said to ease everything from sore joints to stressed minds.',
      'Once you have rinsed the volcanic grey away, we carry on to Toraille, a fifteen-metre waterfall pouring into a garden-ringed pool at the edge of the rainforest. It is cold, clear and exactly what you want after a warm soak.',
      'This tour pairs well with a morning at Sugar Beach or an afternoon in Soufrière town — tell your driver and we will make the day flow.',
    ],
    included: ['Park entry to Sulphur Springs and Toraille', 'Mud bath access', 'Local guide throughout', 'Round-trip transport from your hotel'],
    bring: ['A swimsuit you don’t treasure — the mud stains light fabric', 'Towel', 'Change of clothes', 'Waterproof phone pouch'],
  },
  {
    id: 'sugar-beach',
    title: 'Sugar Beach Day Between the Pitons',
    category: 'beaches',
    blurb: 'A full unhurried day on the island’s most photographed white-sand beach, framed by both Pitons.',
    duration: '5–6 hours',
    group: 'Up to 12 guests',
    maxGuests: 12,
    price: 85,
    pricingUnit: 'person',
    img: 'assets/img/sugar-beach.svg',
    gallery: ['assets/img/sugar-beach.svg', 'assets/img/reef-snorkel.svg', 'assets/img/hero-pitons.svg'],
    times: ['8:30 AM', '10:00 AM'],
    meetingPoint: 'Hotel pickup island-wide, or meet at the Sugar Beach public access in Val des Pitons.',
    description: [
      'Sugar Beach sits in the amphitheatre between Gros and Petit Piton — a crescent of pale sand, calm water and green walls rising on either side. It is the postcard, and it more than earns it.',
      'We handle the part that usually goes wrong: getting there. The road down to Val des Pitons is steep and narrow, and taxis back can be scarce in the afternoon. Your driver drops you at the sand, arranges loungers, and is waiting when you are ready to leave.',
      'The reef at the northern end of the bay is one of the easiest snorkels on the island — masks and fins are in the van. Lunch can be a beach bar roti or a table at the resort restaurant; your driver will point you right.',
    ],
    included: ['Round-trip private transport island-wide', 'Beach chair arrangement', 'Snorkel mask and fins', 'Driver on call all day'],
    bring: ['Swimwear and towel', 'Reef-safe sunscreen', 'Cash or card for lunch', 'Dry bag for valuables'],
  },
  {
    id: 'reef-snorkel',
    title: 'Anse Chastanet Reef Snorkel',
    category: 'beaches',
    blurb: 'Snorkel the protected reef that made Soufrière famous — turtles, trumpetfish and coral gardens metres from shore.',
    duration: '3 hours',
    group: 'Up to 8 guests',
    maxGuests: 8,
    price: 70,
    pricingUnit: 'person',
    img: 'assets/img/reef-snorkel.svg',
    gallery: ['assets/img/reef-snorkel.svg', 'assets/img/sugar-beach.svg', 'assets/img/pigeon-island.svg'],
    times: ['9:00 AM', '1:30 PM'],
    meetingPoint: 'Anse Chastanet beach entrance, Soufrière — hotel pickup available west coast.',
    description: [
      'The reef at Anse Chastanet drops away just beyond the swim line, inside the Soufrière Marine Management Area — a protected zone where the coral is healthy and the fish genuinely do not care that you are there. Hawksbill turtles graze the sea-grass, squid hang in formation, and the volcanic sand makes the water glitter.',
      'A local water guide swims with your group the entire session, pointing out what you would otherwise miss and keeping everyone inside the buoyed area. First-time snorkellers are welcome; flotation vests are standard.',
      'Afternoons are quieter on the reef; mornings are calmer on the road. Either way, this is the easiest world-class snorkel you will ever do.',
    ],
    included: ['Marine reserve fee', 'Mask, snorkel, fins and vest', 'In-water guide', 'Fresh coconut water after the swim'],
    bring: ['Swimwear', 'Towel', 'Reef-safe sunscreen only — it is a protected area', 'Underwater camera if you have one'],
  },
  {
    id: 'tet-paul',
    title: 'Tet Paul Nature Trail',
    category: 'rainforest',
    blurb: 'The famous “Stairway to Heaven” — an easy guided ridge walk with the best Piton viewpoint on the island.',
    duration: '2 hours',
    group: 'Up to 10 guests',
    maxGuests: 10,
    price: 45,
    pricingUnit: 'person',
    img: 'assets/img/tet-paul.svg',
    gallery: ['assets/img/tet-paul.svg', 'assets/img/gros-piton-hike.svg', 'assets/img/about-ridge.svg'],
    times: ['8:00 AM', '10:00 AM', '2:00 PM', '4:00 PM'],
    meetingPoint: 'Tet Paul trailhead, Château Belair, Soufrière — hotel pickup available.',
    description: [
      'If you want the Piton photograph without the four-hour climb, Tet Paul is the answer. This community-run trail loops gently along a ridge above Soufrière, through farmland growing cassava, pineapple and soursop, to a wooden stairway that opens onto both Pitons at once.',
      'Your guide is from the Château Belair community that maintains the trail; the walk is as much about plants, farming and village life as it is about the view. On a clear day you can see Martinique to the north and Saint Vincent to the south.',
      'The path is graded and stepped throughout — manageable for children, grandparents and anyone in reasonable walking shoes.',
    ],
    included: ['Community trail fee', 'Local guide', 'Fresh seasonal fruit tasting', 'Hotel pickup from Soufrière area'],
    bring: ['Walking shoes or solid sandals', 'Hat and sunscreen', 'Water bottle', 'Camera'],
  },
  {
    id: 'rainforest-waterfall',
    title: 'Rainforest & En Bas Saut Falls Hike',
    category: 'rainforest',
    blurb: 'Walk the Edmund Forest Reserve under 20-metre trees to a waterfall pool few visitors ever reach.',
    duration: '4 hours',
    group: 'Up to 8 guests',
    maxGuests: 8,
    price: 80,
    pricingUnit: 'person',
    img: 'assets/img/rainforest-waterfall.svg',
    gallery: ['assets/img/rainforest-waterfall.svg', 'assets/img/botanical-gardens.svg', 'assets/img/about-ridge.svg'],
    times: ['7:30 AM', '9:00 AM'],
    meetingPoint: 'Edmund Forest Reserve ranger station — round-trip transport included island-wide.',
    description: [
      'The interior of Saint Lucia is a different island: cooler, greener, loud with birdsong. The En Bas Saut trail runs through the Edmund Forest Reserve beneath gommier and chatannyé trees, with the Piton Troumassée massif appearing and disappearing through the canopy.',
      'The reward is a two-tier waterfall dropping into a pool cold enough to make you gasp and clear enough to see your toes. Most days you will have it entirely to yourselves.',
      'Along the way your guide calls out the island’s endemic birds — with luck, the Saint Lucia parrot itself, flashes of green and blue crossing the valley. The trail is muddy in stretches and moderately hilly; it rewards proper shoes and an early start.',
    ],
    included: ['Forest reserve entry', 'Naturalist guide', 'Round-trip 4x4 transport', 'Trail snacks and water'],
    bring: ['Shoes with grip that can get muddy', 'Swimwear for the pool', 'Insect repellent', 'Dry change of clothes for the ride home'],
  },
  {
    id: 'botanical-gardens',
    title: 'Diamond Falls & Botanical Gardens',
    category: 'rainforest',
    blurb: 'Saint Lucia’s oldest gardens — mineral-streaked Diamond Falls, hot spring baths and six acres of tropical planting.',
    duration: '2–3 hours',
    group: 'Up to 12 guests',
    maxGuests: 12,
    price: 55,
    pricingUnit: 'person',
    img: 'assets/img/botanical-gardens.svg',
    gallery: ['assets/img/botanical-gardens.svg', 'assets/img/rainforest-waterfall.svg', 'assets/img/sulphur-springs.svg'],
    times: ['9:30 AM', '11:30 AM', '2:00 PM'],
    meetingPoint: 'Diamond Estate, Soufrière — hotel pickup available west coast.',
    description: [
      'The Diamond Estate has been in the same family since the eighteenth century, and its gardens have had two hundred years to grow into themselves — heliconia, torch ginger, breadfruit and cocoa shaded by old mango trees, with hummingbirds working the borders.',
      'At the head of the garden path, Diamond Falls drops seventeen metres down a cliff face painted yellow, green and purple by volcanic minerals — no two visits show the same colours.',
      'The estate’s outdoor mineral baths, first built for the troops of Louis XVI in 1784, are fed by the same underground springs as the Sulphur Springs. A warm soak among the trees is an optional, thoroughly recommended way to finish.',
    ],
    included: ['Garden and waterfall entry', 'Guided garden walk', 'Mineral bath access', 'Hotel pickup from the Soufrière area'],
    bring: ['Swimsuit for the baths', 'Towel', 'Camera', 'Comfortable shoes'],
  },
  {
    id: 'castries-market',
    title: 'Castries Market & Creole Kitchen',
    category: 'culinary',
    blurb: 'Shop the 130-year-old market with a local cook, then turn the basket into a proper Creole lunch together.',
    duration: '4 hours',
    group: 'Up to 8 guests',
    maxGuests: 8,
    price: 65,
    pricingUnit: 'person',
    img: 'assets/img/castries-market.svg',
    gallery: ['assets/img/castries-market.svg', 'assets/img/fish-fry.svg', 'assets/img/rum-distillery.svg'],
    times: ['8:00 AM', '9:30 AM'],
    meetingPoint: 'Castries Central Market clock tower — pickup available from the north of the island.',
    description: [
      'Castries Market has anchored the capital since 1891 — a roofed maze of produce, spice stalls, fish landings and gossip. On a Saturday morning it is the island at full volume, and it is best navigated with someone who knows every vendor by name.',
      'Your host — a Castries cook who learned at her grandmother’s stove — walks you through what is in season and what to smell before you buy. Green fig, saltfish, callaloo, seamoss, cocoa sticks: the basket fills fast.',
      'Then to the kitchen, where the morning’s shopping becomes lunch: green fig and saltfish (the national dish), fresh juice, and whatever the market suggested. You cook, you taste, you eat around one table. Recipes come home with you.',
    ],
    included: ['Market walk with a local cook', 'All ingredients', 'Hands-on cooking session', 'Full Creole lunch with juice'],
    bring: ['Appetite', 'Comfortable shoes for the market', 'A small bag for spices you will inevitably buy', 'Any allergies flagged in advance'],
  },
  {
    id: 'rum-distillery',
    title: 'Roseau Valley Rum Journey',
    category: 'culinary',
    blurb: 'From cane fields to copper stills — tour Saint Lucia’s working distillery and taste the rums it is famous for.',
    duration: '3 hours',
    group: 'Up to 12 guests',
    maxGuests: 12,
    price: 60,
    pricingUnit: 'person',
    img: 'assets/img/rum-distillery.svg',
    gallery: ['assets/img/rum-distillery.svg', 'assets/img/castries-market.svg', 'assets/img/island-day-hire.svg'],
    times: ['10:00 AM', '1:00 PM', '3:00 PM'],
    meetingPoint: 'Roseau Valley distillery gates — round-trip transport included from the north and west.',
    description: [
      'The Roseau Valley has grown sugar cane for three centuries, and its distillery still turns out some of the Caribbean’s most decorated rums. This tour walks the whole line: cane, molasses, fermentation tanks, copper pot stills and the barrel houses where the air itself feels 40% proof.',
      'The guided tasting that follows is generous and unhurried — white rums, aged blends, and the spiced and cream styles the island pours at every fish fry. You will leave understanding why Saint Lucians argue about rum the way the French argue about wine.',
      'Round-trip transport is included, so the tasting can be enjoyed properly. The distillery shop ships internationally — a detail many guests are glad to learn.',
    ],
    included: ['Distillery tour', 'Full guided tasting flight', 'Round-trip transport from the north and west coasts', 'Tasting notes card'],
    bring: ['Photo ID — guests must be 18+ to taste', 'Closed shoes for the production floor', 'Space in your luggage', 'A designated non-taster is welcome free of charge'],
  },
  {
    id: 'fish-fry',
    title: 'Anse La Raye Friday Fish Fry',
    category: 'cultural',
    blurb: 'The island’s original Friday night street feast — grilled fish, cold beer and soca in a west coast fishing village.',
    duration: '4 hours',
    group: 'Up to 10 guests',
    maxGuests: 10,
    price: 55,
    pricingUnit: 'person',
    img: 'assets/img/fish-fry.svg',
    gallery: ['assets/img/fish-fry.svg', 'assets/img/about-village.svg', 'assets/img/castries-market.svg'],
    times: ['6:30 PM', '7:30 PM'],
    meetingPoint: 'Hotel pickup island-wide — the evening runs from roughly 7 PM to 11 PM.',
    description: [
      'Every Friday night, the fishing village of Anse La Raye closes its seafront street, lights the coal pots and cooks what came off the boats that afternoon. Lobster in season, tuna and dorado steaks, bakes, floats, and pots of creole sauce that never quite give up their recipe.',
      'This is not a show staged for visitors — it is the village’s own night out, and it welcomes guests generously. Your host walks you in, introduces you to the stalls worth queuing for, finds you a table and keeps the rum punch honest.',
      'The evening ends when you decide it does; your driver is parked close and sober. Friday nights only — book early in high season.',
    ],
    included: ['Round-trip evening transport island-wide', 'Local host for the evening', 'First drink on us', 'Stall recommendations you can trust'],
    bring: ['Cash in small notes for the stalls', 'An appetite for fish straight off the grill', 'Dancing shoes, loosely defined', 'Mosquito repellent'],
  },
  {
    id: 'pigeon-island',
    title: 'Pigeon Island & North Coast Heritage',
    category: 'cultural',
    blurb: 'Climb Fort Rodney, walk the ruins of a 1778 naval station and swim off the causeway beaches below.',
    duration: '3 hours',
    group: 'Up to 12 guests',
    maxGuests: 12,
    price: 50,
    pricingUnit: 'person',
    img: 'assets/img/pigeon-island.svg',
    gallery: ['assets/img/pigeon-island.svg', 'assets/img/about-coast.svg', 'assets/img/reef-snorkel.svg'],
    times: ['9:00 AM', '11:00 AM', '2:00 PM'],
    meetingPoint: 'Pigeon Island National Landmark gates, Gros Islet — pickup available from Rodney Bay and Castries.',
    description: [
      'Pigeon Island guards the north-west tip of Saint Lucia — forty acres of national landmark where Admiral Rodney watched the French fleet at Martinique before the Battle of the Saintes. The ruins are open to wander: barracks, powder magazines, and the fort at the summit.',
      'The climb to Fort Rodney is short and the payoff is enormous — Rodney Bay curving south, Martinique floating on the northern horizon, and the Caribbean meeting the Atlantic in a visible line of colour.',
      'Below the ruins are two calm, seldom-crowded beaches. Bring a swimsuit, and let the fort’s little café press a cold drink on you. Your guide carries the stories; the island supplies the setting.',
    ],
    included: ['National landmark entry', 'Guided heritage walk', 'Time to swim at the causeway beaches', 'Pickup from Rodney Bay & Castries hotels'],
    bring: ['Walking shoes for the fort climb', 'Swimwear and towel', 'Hat and sunscreen', 'Camera for the summit view'],
  },
  {
    id: 'sunset-cruise',
    title: 'West Coast Sunset Sail',
    category: 'beaches',
    blurb: 'Two golden hours under sail along the Caribbean coast, rum punch in hand, Pitons on the horizon.',
    duration: '2.5 hours',
    group: 'Up to 12 guests',
    maxGuests: 12,
    price: 90,
    pricingUnit: 'person',
    img: 'assets/img/sunset-cruise.svg',
    gallery: ['assets/img/sunset-cruise.svg', 'assets/img/island-day-hire.svg', 'assets/img/hero-pitons.svg'],
    times: ['4:30 PM', '5:00 PM'],
    meetingPoint: 'Rodney Bay Marina, Dock C — hotel pickup available from the north.',
    description: [
      'The west coast of Saint Lucia faces the sunset dead-on, and the only way to improve the view is to be on the water when it happens. We sail south from Rodney Bay past Castries harbour and the fishing villages of the coast, engine off wherever the wind allows.',
      'The crew pours rum punch and juices and hands round hot bakes and saltfish accras as the light turns gold. Dolphins join more evenings than you would guess.',
      'As the sun goes down, the boat turns for home under a sky doing its full production. Bring a light layer — the breeze freshens after dark — and an empty camera roll.',
    ],
    included: ['Two-and-a-half-hour catamaran sail', 'Open bar — rum punch, beer, juices', 'Creole canapés', 'Hotel pickup from the north of the island'],
    bring: ['Light jacket or wrap for after sunset', 'Flat shoes or bare feet on deck', 'Camera', 'Motion tablets if you are cautious at sea'],
  },
  {
    id: 'airport-transfer',
    title: 'Private Airport Transfer',
    category: 'transfers',
    blurb: 'A verified local driver, waiting at arrivals with your name — Hewanorra or George F. L. Charles, any hotel.',
    duration: '30–90 min',
    group: 'Up to 6 per vehicle',
    maxGuests: 6,
    price: 80,
    pricingUnit: 'vehicle',
    img: 'assets/img/airport-transfer.svg',
    gallery: ['assets/img/airport-transfer.svg', 'assets/img/about-coast.svg', 'assets/img/about-village.svg'],
    times: ['Matched to your flight'],
    meetingPoint: 'Arrivals hall — your driver waits with a name board, tracking your flight.',
    description: [
      'The drive from Hewanorra International to the resorts of the north coast takes about ninety minutes over the island’s spine — a beautiful ride, and a terrible thing to negotiate at a taxi rank after nine hours of travel. We remove the negotiation.',
      'Your driver is licensed, vetted, and tracking your flight before you land. If you are delayed, they wait; the fare does not change. The vehicle is air-conditioned, the water is cold, and the first views of the coast road come with commentary if you want it — or quiet if you don’t.',
      'Fixed fares are quoted per vehicle, not per person, and confirmed before you fly. See the full fare guide on our Transfers page.',
    ],
    included: ['Meet and greet at arrivals with name board', 'Flight tracking — no charge for delays', 'Air-conditioned vehicle, up to 6 guests', 'Bottled water and island orientation en route'],
    bring: ['Your hotel name and flight number at booking', 'Nothing else — the driver handles the bags'],
  },
  {
    id: 'island-day-hire',
    title: 'Private Driver Day Hire',
    category: 'transfers',
    blurb: 'Your own driver and vehicle for a full day — build the island itinerary you actually want.',
    duration: '8 hours',
    group: 'Up to 6 per vehicle',
    maxGuests: 6,
    price: 220,
    pricingUnit: 'vehicle',
    img: 'assets/img/island-day-hire.svg',
    gallery: ['assets/img/island-day-hire.svg', 'assets/img/sunset-cruise.svg', 'assets/img/airport-transfer.svg'],
    times: ['8:00 AM', '9:00 AM', '10:00 AM'],
    meetingPoint: 'Your hotel lobby, anywhere on the island.',
    description: [
      'Some days refuse to fit a tour: a morning at the volcano, lunch at a bakery someone mentioned, an hour at a beach with no name on the map, back in time for dinner. For those days you want a driver, not a schedule.',
      'Day hire gives you a licensed driver-guide and an air-conditioned vehicle for eight hours, routed however you like. Our drivers know the roadside fruit stands, the viewpoints without tour buses, and which beach bars are actually open on a Tuesday.',
      'Tell us roughly what you have in mind — or tell us nothing and let your driver propose a day. Entry fees and lunch are the only things not included; fuel, mileage and local knowledge are.',
    ],
    included: ['Licensed driver-guide for 8 hours', 'Air-conditioned vehicle, fuel and mileage', 'Flexible routing, planned or spontaneous', 'Cooler with water and soft drinks'],
    bring: ['Ideas, or none at all', 'Cash for site entry fees and lunch', 'Swimwear — a beach always finds its way in', 'Camera'],
  },
];

/* Alt text for each experience's lead image, keyed by id. */
const IMAGE_ALT = {
  'gros-piton-hike': 'Gros Piton towering above hazy ridgelines under a bright morning sky',
  'sulphur-springs': 'Steam-softened volcanic hills of the Sulphur Springs with a waterfall threading down the ridge',
  'sugar-beach': 'White sand and calm turquoise water at Sugar Beach, the Pitons rising beyond the bay',
  'reef-snorkel': 'Deep green reef water at Anse Chastanet with two small boats at anchor offshore',
  'tet-paul': 'Both Pitons seen from the Tet Paul ridge, farmland hills in the foreground',
  'rainforest-waterfall': 'A waterfall dropping through misty layers of Saint Lucian rainforest canopy',
  'botanical-gardens': 'Lush terraced gardens and a slender waterfall at the Diamond Botanical Gardens',
  'castries-market': 'Fishing boats resting in Castries harbour in warm early light, hills behind the town',
  'rum-distillery': 'Amber evening light over rolling sugar cane hills in the Roseau Valley',
  'fish-fry': 'Lantern lights of the Anse La Raye fish fry glowing along a twilight shoreline',
  'pigeon-island': 'The green headland of Pigeon Island above a pale causeway beach and anchored sailboat',
  'sunset-cruise': 'A catamaran under sail on gilded water as the sun sinks toward the horizon near the Pitons',
  'airport-transfer': 'The west coast road winding above the Caribbean Sea between green headlands',
  'island-day-hire': 'Golden-hour light over the west coast, palms leaning above a quiet bay',
};
EXPERIENCES.forEach((e) => { e.alt = IMAGE_ALT[e.id] || e.title; });

/* Fixed-fare transfer routes shown on the Transfers page. */
const TRANSFER_ROUTES = [
  { from: 'Hewanorra Intl. (UVF)', to: 'Rodney Bay / Gros Islet', fare: 90, duration: '≈ 90 min' },
  { from: 'Hewanorra Intl. (UVF)', to: 'Castries', fare: 80, duration: '≈ 75 min' },
  { from: 'Hewanorra Intl. (UVF)', to: 'Soufrière', fare: 75, duration: '≈ 60 min' },
  { from: 'Hewanorra Intl. (UVF)', to: 'Marigot Bay', fare: 80, duration: '≈ 70 min' },
  { from: 'George F. L. Charles (SLU)', to: 'Castries', fare: 25, duration: '≈ 10 min' },
  { from: 'George F. L. Charles (SLU)', to: 'Rodney Bay', fare: 35, duration: '≈ 25 min' },
  { from: 'Rodney Bay', to: 'Soufrière', fare: 95, duration: '≈ 80 min' },
  { from: 'Castries', to: 'Marigot Bay', fare: 45, duration: '≈ 30 min' },
];

/* Pickup areas offered in the booking flow. */
const PICKUP_AREAS = [
  'Rodney Bay / Gros Islet',
  'Castries',
  'Marigot Bay',
  'Anse La Raye',
  'Soufrière',
  'Vieux Fort',
  'Hewanorra Airport (UVF)',
  'George F. L. Charles Airport (SLU)',
  'Other / not sure yet',
];

function getExperience(id) {
  return EXPERIENCES.find((e) => e.id === id) || null;
}

function formatPrice(exp) {
  return `US$${exp.price}`;
}

function priceUnitLabel(exp) {
  return exp.pricingUnit === 'vehicle' ? 'per vehicle' : 'per person';
}
